<center>
<img src="https://drive.google.com/uc?id=1f1gGVI-rxcHjA90WEGNvvtSXF1pAxQwg" alt="Fasilkom UI" width="300"/>

CSGE603130 • Kecerdasan Artifisial dan Sains Data Dasar

Semester Gasal 2023/2024

Fakultas Ilmu Komputer, Universitas Indonesia

##**Lab 1: *Pandas dan Numpy***

###**Tenggat Waktu: Selasa, 3 September 2024, 23.55 WIB**
</center>

### **Ketentuan:**

1. Dokumen template lab dengan format .ipynb dan dataset (jika dibutuhkan) telah disediakan di SCeLe
2. Jalankan kode pada dokumen .ipynb dan perhatikan dengan saksama apa yang potongan kode tersebut lakukan beserta dengan keluarannya. Jawablah **pertanyaan** yang disisipkan pada potongan program yang diberikan.
3. Dokumen Jupyter Notebook yang telah dilengkapi dengan jawaban dikumpulkan dengan format penamaan **Kelas_LabX_NPM_Nama.ipynb** . Contoh: A_Lab1_1806205773_Abdurrafi Arief.ipynb. Kesalahan dalam pengumpulan nama akan dikenakan pinalti sebesar 5 poin.
4. Kumpulkan dokumen tersebut pada submisi yang telah disediakan di SCeLe sesuai dengan kelas masing-masing sebelum **Tenggat Waktu: Selasa, 3 September 2024, 23.55 WIB**.
5. Keterlambatan pengumpulan akan dikenakan pinalti sebesar 5 poin per jam. Dengan cut off 1 hari.
6. Lab ini dirancang sebagai **tugas mandiri**. Plagiarisme tidak diperkenankan dalam bentuk apapun. Adapun kolaborasi berupa diskusi (tanpa menyalin maupun mengambil jawaban orang lain) dan literasi masih diperbolehkan dengan mencantumkan kolaborator dan sumber.
7. Pakta Integritas **Wajib** di isi dan di jalankan. Submisi hanya akan dinilai jika pakta integritas di isi dan di jalankan.
8. Sebelum di kumpulkan, kode **WAJIB** dijalankan. Jika tidak, dikenakan penalti sebesar 50%.

### **Sumber:**

1. Sebagian besar materi Lab ini diambil dari Lab beberapa semester-semester sebelumnya dengan modifikasi.
2. Sumber internet lain yang digunakan juga telah dicantumkan sebagai *hyperlink* pada teks.

In [1]:
# Isi dengan data diri Anda
NAMA = ""
KELAS = ""
NPM = ""
USERNAME_KAGGLE = ""

# Isi dengan NPM teman yang berdiskusi dengan Anda
KOLABORATOR = []

# Isi dengan sumber referensi yang Anda gunakan dalam mengerjakan
REFERENSI = []

In [2]:
PERNYATAAN_INTEGRITAS = "Saya, %s dari kelas %s dengan NPM %s, menyatakan bahwa seluruh jawaban pada pekerjaan ini murni saya kerjakan sendiri.\n\
Saya tidak mencontek jawaban, memberikan jawaban, maupun menyalin dari sumber manapun.\n \
\n\
Jika saya melanggar pernyataan tersebut, saya siap menerima konsekuensi apapun yang diberikan.\n   \
(%s)" % (NAMA, KELAS, NPM, NAMA)

print(PERNYATAAN_INTEGRITAS)

Saya,  dari kelas  dengan NPM , menyatakan bahwa seluruh jawaban pada pekerjaan ini murni saya kerjakan sendiri.
Saya tidak mencontek jawaban, memberikan jawaban, maupun menyalin dari sumber manapun.
 
Jika saya melanggar pernyataan tersebut, saya siap menerima konsekuensi apapun yang diberikan.
   ()


# **Memahami Python (kembali) 🐍**

Untuk dapat mengerjakan soal lab KASDAD, kamu perlu memahami bahasa pemrograman Python. Bagi kamu yang membutuhkan pemahaman Python (lagi), yuk kunjungi playlist YouTube [**DDP 1 MOOC UI**](https://bit.ly/pymooc-id) yang telah dibuat oleh Pak Fariz!

# **Jupyter Notebook (`.ipynb`)**

Berbeda dengan file Python pada umumnya, kali ini kita akan menggunakan file [**Jupyter Notebook**](https://ipython.org/notebook.html), yang memiliki ekstensi `.ipynb`. Dengan file `.ipynb`, kita dapat menyimpan berbagai jenis informasi dalam bentuk ***cell***, seperti kode dalam bahasa Python (atau R), output hasil eksekusi kode tersebut, dan teks deskriptif dalam format ***Markdown***. Untuk membuat dan mengedit file `.ipynb`, kita bisa menggunakan *tools* seperti JupyterLab atau Google Colab yang cukup umum digunakan. Jupyter Notebook memungkinkan kita untuk berinteraksi dengan informasi-informasi tersebut secara interaktif.

Sebagai contoh, berikut adalah *cell* untuk menuliskan kode dalam bahasa Python. Dalam satu file, setiap kode dalam *cell* berada pada satu *environment* yang sama sehingga setiap *cell* yang melibatkan variabel yang sama akan berkaitan dan urutan eksekusi mungkin berpengaruh. Untuk menjalankan *cell*, kamu bisa menekan tombol "**Run**" yang tersedia atau menggunakan kombinasi shortcut ***Shift + Enter***. Setelah dieksekusi, outputnya akan ditampilkan di bagian bawah *cell*.

In [3]:
# Contoh cell untuk kode Python, gunakan jenis cell ini untuk mengeksekusi
# kode yang diperlukan

var = "Hello, world!"
print(var)
var

Hello, world!


'Hello, world!'

Sedangkan ini adalah contoh *cell* untuk teks *Markdown*, klik 2 kali untuk meng-edit setiap ***cell***. Gunakan jenis *cell* ini untuk memberikan penjelasan terhadap setiap soal yang dikerjakan.

_Markdown_ adalah _markup language_ yang digunakan untuk membuat teks berformat menggunakan _text editor_ biasa. Dengan _Markdown_, kita dapat membuat berbagai gaya teks, seperti _heading_, _hyperlink_, tabel, _list_, dan masih banyak lagi. Contoh berbagai sintaks _Markdown_ dapat dilihat pada [panduan dari Markdownguide.org](https://www.markdownguide.org/.cheat-sheet/) dan [wiki oleh Adam Pritchard](https://github.com/adam-p/markdown-here/wiki/Markdown-Here-Cheatsheet).[link text](https://)

## Instalasi library pada Jupyter Notebook

Secara umum, tools seperti JupyterLab atau Google Colab telah menyediakan *kernel* yang dilengkapi dengan beberapa *library* Python. Namun, untuk menginstal *library* tambahan yang dibutuhkan, kita dapat menjalankan perintah `pip install nama-package` pada *cell* kode. Sebagai contoh, berikut adalah *cell* untuk menginstall *library* **Pandas**.

In [ ]:
!pip install pandas

Selain untuk menjalankan `pip`, kernel ini juga dapat menerima perintah sistem lain seperti `git` ataupun `apt`, tergantung pada kompatibilitas dan konfigurasi kernel tersebut.

# **Pandas**

[__Pandas__](https://pandas.pydata.org/docs/) adalah _library_ pada bahasa Python yang menyediakan struktur data dan fungsi-fungsi yang mempermudah pemrosesan dan analisis data. Library ini sangat umum digunakan dalam pengolahan data karena kemampuannya dalam menangani data dengan efisien dan intuitif.

In [4]:
# import library
import pandas as pd

## ***Series***

Dalam *library* Pandas, terdapat [***series***](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html) yang digunakan untuk menyimpan koleksi data **satu** dimensi, mirip dengan *array* pada bahasa pemrograman umumnya. *Series* juga memiliki index yang dimulai dari 0 hingga N-1 dengan N adalah jumlah elemen pada *series* tersebut sehingga memampukan kita untuk melakkuan *indexing* dan *slicing* data. Sama seperti array, *series* dapat menyimpan elemen dengan berbagai jenis data, seperti *integer*, *string*, *float*, dan lainnya.

Salah satu cara yang umum digunakan untuk membuat objek **Series** adalah sebagai berikut:
```
pd.Series(data)
```
Di mana `data` dapat berupa list, tuple, atau dictionary.

In [5]:
# Contoh pembuatan objek Series dari sebuah tuple
series = pd.Series((10, 20, 30, 40, 50))
series

0    10
1    20
2    30
3    40
4    50
dtype: int64

Saat *series* di atas ditampilkan sebagai output, terdapat dua buah kolom: kolom sebelah kiri merupakan `index` dan kolom sebelah kanannya adalah `values` yang berkorespondensi satu sama lain.

In [6]:
# Contoh melakukan indexing pada objek Series
series[2]

30

In [9]:
# Contoh melakukan slicing pada objek Series
series[:3]

0    10
1    20
2    30
dtype: int64

## ***DataFrame***

Untuk menyimpan data yang berdimensi dua seperti tabel, kita bisa menggunakan objek [***DataFrame***](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html). Setiap data disimpan pada pasangan *index* (baris) dan *column* (kolom) yang unik. Setiap *column* pada *DataFrame* dapat menyimpan suatu tipe data yang berbeda-beda seperti *integer*, *string*, atau *float* sehingga memungkinkan menyimpan data yang variatif.

Untuk membuat objek *DataFrame*, kita bisa menggunakan data dari berbagai struktur data dan sumber file, seperti kumpulan list, tuple, *Series*, CSV, Excel, dan SQL. *Syntax* umum untuk membuat objek DataFrame adalah sebagai berikut:

```
pd.DataFrame(data, columns=column_names)
```

`data` dapat berupa list, tuple, dictionary, atau *Series*
`column_names` berupa list yang berisi daftar nama kolom yang berurutan. Jika tidak diberikan, nama kolom akan dihasilkan secara otomatis sebagai integer mulai dari 0

### Membuat *DataFrame* dari *Series*

In [ ]:
series = pd.Series(["apel", "mangga", "jeruk", "lemon"])
series

0      apel
1    mangga
2     jeruk
3     lemon
dtype: object

In [ ]:
df = pd.DataFrame(series, columns=["Buah"])
df

Buah
0    apel
1  mangga
2   jeruk
3   lemon

### Membuat *DataFrame* dari *Dictionary of Series*

In [ ]:
indonesia = pd.Series(["apel", "mangga", "jeruk", "lemon"])
indonesia

0      apel
1    mangga
2     jeruk
3     lemon
dtype: object

In [ ]:
english = pd.Series(["apple", "mango", "orange", "lemon"])
english

0     apple
1     mango
2    orange
3     lemon
dtype: object

In [ ]:
df = pd.DataFrame({
    "indonesia": indonesia,
    "english": english
})
df

indonesia english
0      apel   apple
1    mangga   mango
2     jeruk  orange
3     lemon   lemon

### Membuat *DataFrame* dari *File*

In [10]:
# Membuat DataFrame dari file csv

df = pd.read_csv(
    "https://archive.ics.uci.edu/ml/machine-learning-databases/abalone/abalone.data", # URL file ataupun file path (absolute ataupun local)
    header=None, # None jika baris pertama bukan header
)
df

0      1      2      3       4       5       6       7   8
0     M  0.455  0.365  0.095  0.5140  0.2245  0.1010  0.1500  15
1     M  0.350  0.265  0.090  0.2255  0.0995  0.0485  0.0700   7
2     F  0.530  0.420  0.135  0.6770  0.2565  0.1415  0.2100   9
3     M  0.440  0.365  0.125  0.5160  0.2155  0.1140  0.1550  10
4     I  0.330  0.255  0.080  0.2050  0.0895  0.0395  0.0550   7
...  ..    ...    ...    ...     ...     ...     ...     ...  ..
4172  F  0.565  0.450  0.165  0.8870  0.3700  0.2390  0.2490  11
4173  M  0.590  0.440  0.135  0.9660  0.4390  0.2145  0.2605  10
4174  M  0.600  0.475  0.205  1.1760  0.5255  0.2875  0.3080   9
4175  F  0.625  0.485  0.150  1.0945  0.5310  0.2610  0.2960  10
4176  M  0.710  0.555  0.195  1.9485  0.9455  0.3765  0.4950  12

[4177 rows x 9 columns]

Dataset di atas diambil dari [Abalone](https://archive.ics.uci.edu/dataset/1/abalone) yang berisi data kerang abalon. Untuk dapat memahami data lebih baik, kita bisa memberikan nama column yang lebih intuitif sebagai berikut:

In [11]:
df.columns = [
    'Sex', 'Length', 'Diameter', 'Height',
    'Whole_weight', 'Shucked_weight', 'Viscre_weight', 'Shell_weight', 'Rings'
]
df

Sex  Length  Diameter  Height  Whole_weight  Shucked_weight  \
0      M   0.455     0.365   0.095        0.5140          0.2245   
1      M   0.350     0.265   0.090        0.2255          0.0995   
2      F   0.530     0.420   0.135        0.6770          0.2565   
3      M   0.440     0.365   0.125        0.5160          0.2155   
4      I   0.330     0.255   0.080        0.2050          0.0895   
...   ..     ...       ...     ...           ...             ...   
4172   F   0.565     0.450   0.165        0.8870          0.3700   
4173   M   0.590     0.440   0.135        0.9660          0.4390   
4174   M   0.600     0.475   0.205        1.1760          0.5255   
4175   F   0.625     0.485   0.150        1.0945          0.5310   
4176   M   0.710     0.555   0.195        1.9485          0.9455   

      Viscre_weight  Shell_weight  Rings  
0            0.1010        0.1500     15  
1            0.0485        0.0700      7  
2            0.1415        0.2100      9  
3            0.1140        0.1550     10  
4            0.0395        0.0550      7  
...             ...           ...    ...  
4172         0.2390        0.2490     11  
4173         0.2145        0.2605     10  
4174         0.2875        0.3080      9  
4175         0.2610        0.2960     10  
4176         0.3765        0.4950     12  

[4177 rows x 9 columns]

- **Sex**: Jenis kelamin kerang (M, F, dan I untuk *infant*)
- **Length**: Panjang kerang
- **Diameter**: Diameter kerang yang tegak lurus dengan panjang
- **Height**: Tinggi kerang dengan daging dalam cangkang
- **Whole_weight**: Berat keseluruhan kerang
- **Shucked_weight**: Berat daging tanpa kerang
- **Viscera_weight**: Berat usus (setelah berdiri)
- **Shell_weight**: Berat cangkang setelah kering
- **Rings**: Jumlah cincin dalam cangkang yang dapat digunakan untuk menghitung umur

### Melihat Cuplikan *DataFrame*

Untuk data yang berukuran besar, melihat keseluruhan data mungkin membutuhkan waktu yang lama serta tampilan yang besar. Kita bisa menggunakan fungsi `head(n)` dan `tail(n)` untuk melihat `n` baris pertama dan terakhir secara berturut-turut. Nilai default untuk `n` adalah 5. Selain itu, kita juga bisa menggunakan fungsi `sample(n)` untuk mengambil `n` *random sample* dari *DataFrame*.

In [ ]:
df.head() # Menampilkan 5 baris pertama dari DataFrame

Sex  Length  Diameter  Height  Whole_weight  Shucked_weight  Viscre_weight  \
0   M   0.455     0.365   0.095        0.5140          0.2245         0.1010   
1   M   0.350     0.265   0.090        0.2255          0.0995         0.0485   
2   F   0.530     0.420   0.135        0.6770          0.2565         0.1415   
3   M   0.440     0.365   0.125        0.5160          0.2155         0.1140   
4   I   0.330     0.255   0.080        0.2050          0.0895         0.0395   

   Shell_weight  Rings  
0         0.150     15  
1         0.070      7  
2         0.210      9  
3         0.155     10  
4         0.055      7

In [ ]:
df.head(3) # Menampilkan 3 baris pertama dari DataFrame

Sex  Length  Diameter  Height  Whole_weight  Shucked_weight  Viscre_weight  \
0   M   0.455     0.365   0.095        0.5140          0.2245         0.1010   
1   M   0.350     0.265   0.090        0.2255          0.0995         0.0485   
2   F   0.530     0.420   0.135        0.6770          0.2565         0.1415   

   Shell_weight  Rings  
0          0.15     15  
1          0.07      7  
2          0.21      9

In [ ]:
df.tail() # Menampilkan 5 baris terakhir dari DataFrame

Sex  Length  Diameter  Height  Whole_weight  Shucked_weight  \
4172   F   0.565     0.450   0.165        0.8870          0.3700   
4173   M   0.590     0.440   0.135        0.9660          0.4390   
4174   M   0.600     0.475   0.205        1.1760          0.5255   
4175   F   0.625     0.485   0.150        1.0945          0.5310   
4176   M   0.710     0.555   0.195        1.9485          0.9455   

      Viscre_weight  Shell_weight  Rings  
4172         0.2390        0.2490     11  
4173         0.2145        0.2605     10  
4174         0.2875        0.3080      9  
4175         0.2610        0.2960     10  
4176         0.3765        0.4950     12

In [13]:
df.sample(5) # Menampilkan 5 baris random dari DataFrame

Sex  Length  Diameter  Height  Whole_weight  Shucked_weight  \
2409   F   0.640      0.50   0.150        1.0705          0.3710   
2759   F   0.545      0.44   0.150        0.9475          0.3660   
3148   F   0.710      0.53   0.195        1.8745          0.6755   
1543   I   0.365      0.27   0.085        0.2225          0.0935   
2473   F   0.615      0.47   0.175        1.2985          0.5135   

      Viscre_weight  Shell_weight  Rings  
2409         0.2705        0.3600      8  
2759         0.2390        0.2750      8  
3148         0.4065        0.6855     12  
1543         0.0525        0.0660      7  
2473         0.3430        0.3200     14

### Melihat Informasi *DataFrame*

Selain melihat data pada *DataFrame*, kita juga bisa melihat properti atau metadata yang ada pada setiap objek *DataFrame*, seperti dimensi, tipe data setiap *column*, statistik deskriptif, dan informasi lainnya.

In [ ]:
# Menampilkan dimensi DataFrame

print(f"Dimensi dari DataFrame Abalone adalah: {df.shape}")
print(f"Terdiri dari {df.shape[0]} baris dan {df.shape[1]} kolom")

Dimensi dari DataFrame Abalone adalah: (4177, 9)
Terdiri dari 4177 baris dan 9 kolom


In [ ]:
# Menampilkan tipe data setiap kolom

df.dtypes

Sex                object
Length            float64
Diameter          float64
Height            float64
Whole_weight      float64
Shucked_weight    float64
Viscre_weight     float64
Shell_weight      float64
Rings               int64
dtype: object

In [ ]:
# Menampilkan statistik deskriptif untuk setiap kolom yang merupakan angka

df.describe()

Length     Diameter       Height  Whole_weight  Shucked_weight  \
count  4177.000000  4177.000000  4177.000000   4177.000000     4177.000000   
mean      0.523992     0.407881     0.139516      0.828742        0.359367   
std       0.120093     0.099240     0.041827      0.490389        0.221963   
min       0.075000     0.055000     0.000000      0.002000        0.001000   
25%       0.450000     0.350000     0.115000      0.441500        0.186000   
50%       0.545000     0.425000     0.140000      0.799500        0.336000   
75%       0.615000     0.480000     0.165000      1.153000        0.502000   
max       0.815000     0.650000     1.130000      2.825500        1.488000   

       Viscre_weight  Shell_weight        Rings  
count    4177.000000   4177.000000  4177.000000  
mean        0.180594      0.238831     9.933684  
std         0.109614      0.139203     3.224169  
min         0.000500      0.001500     1.000000  
25%         0.093500      0.130000     8.000000  
50%         0.171000      0.234000     9.000000  
75%         0.253000      0.329000    11.000000  
max         0.760000      1.005000    29.000000

In [ ]:
# Menampilkan statistik deskriptif untuk kolom spesifik

df['Length'].describe()

count    4177.000000
mean        0.523992
std         0.120093
min         0.075000
25%         0.450000
50%         0.545000
75%         0.615000
max         0.815000
Name: Length, dtype: float64

In [ ]:
# Menghitung jumlah nilai yang null (missing values) pada setiap kolom

df.isnull().sum()

Sex               0
Length            0
Diameter          0
Height            0
Whole_weight      0
Shucked_weight    0
Viscre_weight     0
Shell_weight      0
Rings             0
dtype: int64

### Mengakses *Index* (Baris) dan *Column* pada *DataFrame*

Terdapat beberapa cara untuk mengakses suatu atau sekumpulan data pada DataFrame dengan memanfaatkan informasi *index* dan *column*:

#### Mengakses *Column* dengan *Square Bracket*

Kita dapat mengakses satu atau beberapa column menggunakan *syntax square bracket* (`[]`), mirip seperti pada *List* atau *Series*. Apabila hanya menggunakan satu square bracket, maka yang dihasilkan adalah sebuah Series tetapi hanya bisa menyimpan satu column. Dengan dua square bracket, kita bisa menghasilkan DataFrame baru.

In [14]:
# Mengakses satu column dan menghasilkan Series

Rings_series = df['Rings']
print(f"Rings_series merupakan {type(Rings_series)}")
Rings_series

Rings_series merupakan <class 'pandas.core.series.Series'>


0       15
1        7
2        9
3       10
4        7
        ..
4172    11
4173    10
4174     9
4175    10
4176    12
Name: Rings, Length: 4177, dtype: int64

In [15]:
# Mengakses satu column dan menghasilkan DataFrame

Rings_df = df[['Rings']]
print(f"Rings_df merupakan {type(Rings_df)}")
Rings_df

Rings_df merupakan <class 'pandas.core.frame.DataFrame'>


Rings
0        15
1         7
2         9
3        10
4         7
...     ...
4172     11
4173     10
4174      9
4175     10
4176     12

[4177 rows x 1 columns]

In [16]:
# Mengakses beberapa column dan menghasilkan DataFrame

Length_Rings_df = df[['Length', 'Rings']]
print(f"Length_Rings_df merupakan {type(Length_Rings_df)}")
Length_Rings_df

Length_Rings_df merupakan <class 'pandas.core.frame.DataFrame'>


Length  Rings
0      0.455     15
1      0.350      7
2      0.530      9
3      0.440     10
4      0.330      7
...      ...    ...
4172   0.565     11
4173   0.590     10
4174   0.600      9
4175   0.625     10
4176   0.710     12

[4177 rows x 2 columns]

#### Mengakses *Column* dengan *Dot Notation*

Untuk mengakses satu *column* yang menghasilkan *Series*, kita bisa menggunakan *dot notation*, asalkan nama *column* tersebut memenuhi [*Python variable naming rules*](https://peps.python.org/pep-0008/)

In [ ]:
df.Rings

0       15
1        7
2        9
3       10
4        7
        ..
4172    11
4173    10
4174     9
4175    10
4176    12
Name: Rings, Length: 4177, dtype: int64

#### Mengakses *Index* (Baris) dan Column Menggunakan Fungsi `loc` dan `iloc`

Fungi `loc` digunakan untuk mengakses data berdasarkan label dari *index* atau *column* dengan *range* inklusif. Sedangkan fungsi `iloc` digunakan untuk mengakses data berdasarkan posisi bilangan bulat *index* atau *column* (0 sampai jumlah baris - 1).

In [ ]:
# Mengakses data dengan label index dan column
df.loc[0:5, 'Length':'Rings'] # Baris 0 sampai 5, dari kolom Length hingga Rings

Length  Diameter  Height  Whole_weight  Shucked_weight  Viscre_weight  \
0   0.455     0.365   0.095        0.5140          0.2245         0.1010   
1   0.350     0.265   0.090        0.2255          0.0995         0.0485   
2   0.530     0.420   0.135        0.6770          0.2565         0.1415   
3   0.440     0.365   0.125        0.5160          0.2155         0.1140   
4   0.330     0.255   0.080        0.2050          0.0895         0.0395   
5   0.425     0.300   0.095        0.3515          0.1410         0.0775   

   Shell_weight  Rings  
0         0.150     15  
1         0.070      7  
2         0.210      9  
3         0.155     10  
4         0.055      7  
5         0.120      8

In [ ]:
df.loc[:, ['Length', 'Rings']] # Seluruh baris, kolom Length dan Rings saja

Length  Rings
0      0.455     15
1      0.350      7
2      0.530      9
3      0.440     10
4      0.330      7
...      ...    ...
4172   0.565     11
4173   0.590     10
4174   0.600      9
4175   0.625     10
4176   0.710     12

[4177 rows x 2 columns]

In [ ]:
# Mengakses data dengan posisi bilangan bulat index dan column
df.iloc[0:6, 1:9] # Dari baris 0 sampai 5, dari kolom Length sampai Rings

Length  Diameter  Height  Whole_weight  Shucked_weight  Viscre_weight  \
0   0.455     0.365   0.095        0.5140          0.2245         0.1010   
1   0.350     0.265   0.090        0.2255          0.0995         0.0485   
2   0.530     0.420   0.135        0.6770          0.2565         0.1415   
3   0.440     0.365   0.125        0.5160          0.2155         0.1140   
4   0.330     0.255   0.080        0.2050          0.0895         0.0395   
5   0.425     0.300   0.095        0.3515          0.1410         0.0775   

   Shell_weight  Rings  
0         0.150     15  
1         0.070      7  
2         0.210      9  
3         0.155     10  
4         0.055      7  
5         0.120      8

In [ ]:
df.iloc[:, [1, 8]] # Seluruh baris, kolom Length dan Rings saja

Length  Rings
0      0.455     15
1      0.350      7
2      0.530      9
3      0.440     10
4      0.330      7
...      ...    ...
4172   0.565     11
4173   0.590     10
4174   0.600      9
4175   0.625     10
4176   0.710     12

[4177 rows x 2 columns]

### Mengakses Data dengan Suatu Kondisi

Dalam mengolah data, kita cenderung hanya ingin mengakses sebagian data yang memenuhi satu atau beberapa kondisi tertentu. Kita bisa menggunakan `syntax square bracket` (`[]`) untuk melakukan hal tersebut.

In [ ]:
# Mengakses data dengan jenis kelamin laki-laki
df[df['Sex'] == 'M']

Sex  Length  Diameter  Height  Whole_weight  Shucked_weight  \
0      M   0.455     0.365   0.095        0.5140          0.2245   
1      M   0.350     0.265   0.090        0.2255          0.0995   
3      M   0.440     0.365   0.125        0.5160          0.2155   
8      M   0.475     0.370   0.125        0.5095          0.2165   
11     M   0.430     0.350   0.110        0.4060          0.1675   
...   ..     ...       ...     ...           ...             ...   
4170   M   0.550     0.430   0.130        0.8395          0.3155   
4171   M   0.560     0.430   0.155        0.8675          0.4000   
4173   M   0.590     0.440   0.135        0.9660          0.4390   
4174   M   0.600     0.475   0.205        1.1760          0.5255   
4176   M   0.710     0.555   0.195        1.9485          0.9455   

      Viscre_weight  Shell_weight  Rings  
0            0.1010        0.1500     15  
1            0.0485        0.0700      7  
3            0.1140        0.1550     10  
8            0.1125        0.1650      9  
11           0.0810        0.1350     10  
...             ...           ...    ...  
4170         0.1955        0.2405     10  
4171         0.1720        0.2290      8  
4173         0.2145        0.2605     10  
4174         0.2875        0.3080      9  
4176         0.3765        0.4950     12  

[1528 rows x 9 columns]

In [18]:
# Mengakses data dengan jenis kelamin laki-laki dengan jumlah cincin kurang sama dengan 10
df[(df['Sex'] == 'M') & (df['Rings'] <= 10)]

Sex  Length  Diameter  Height  Whole_weight  Shucked_weight  \
1      M   0.350     0.265   0.090        0.2255          0.0995   
3      M   0.440     0.365   0.125        0.5160          0.2155   
8      M   0.475     0.370   0.125        0.5095          0.2165   
11     M   0.430     0.350   0.110        0.4060          0.1675   
18     M   0.365     0.295   0.080        0.2555          0.0970   
...   ..     ...       ...     ...           ...             ...   
4169   M   0.520     0.385   0.165        0.7910          0.3750   
4170   M   0.550     0.430   0.130        0.8395          0.3155   
4171   M   0.560     0.430   0.155        0.8675          0.4000   
4173   M   0.590     0.440   0.135        0.9660          0.4390   
4174   M   0.600     0.475   0.205        1.1760          0.5255   

      Viscre_weight  Shell_weight  Rings  
1            0.0485        0.0700      7  
3            0.1140        0.1550     10  
8            0.1125        0.1650      9  
11           0.0810        0.1350     10  
18           0.0430        0.1000      7  
...             ...           ...    ...  
4169         0.1800        0.1815     10  
4170         0.1955        0.2405     10  
4171         0.1720        0.2290      8  
4173         0.2145        0.2605     10  
4174         0.2875        0.3080      9  

[871 rows x 9 columns]

### Menangani *Missing Values*

Pada dataset, terkadang kita menemukan data yang tidak lengkap yang umumnya ditandai dengan `null`, `NA`, atau `NaN`. Hal ini dapat disebabkan oleh berbagai alasan, seperti data yang tidak tersedia walaupun sebenarnya ada atau memang tidak ada sama sekali. Untuk menangani nilai yang hilang, kita bisa menggunakan berbagai fungsi dalam Pandas.

**Mengidentifikasi *Missing Values***

Pertama-tama, mari membuka file `player_playing_time.csv` yang ada di SCeLE. Dataset ini diambil dari [🏆 UEFA EURO 2024 Database](https://www.kaggle.com/datasets/mexwell/uefa-euro-2024-database) yang merupakan kumpulan data dari pemain-pemain yang berlaga pada turnamen UEFA Euro 2024 kemarin.



In [19]:
df2 = pd.read_csv("player_playing_time.csv")

# Menampilkan jumlah missing value per kolom
df2.isna().sum()

Rk            0
Player        0
Pos           0
Squad         0
Age           0
Born          0
MP            0
Min         128
Mn/MP       128
Min%        123
90s         123
Starts        0
Mn/Start    243
Compl         0
Subs          0
Mn/Sub      364
unSub         0
PPM         123
onG         123
onGA        123
+/-         123
+/-90       128
On-Off      209
onxG        128
onxGA       128
xG+/-       128
xG+/-90     130
On-Off.1    185
Matches       0
dtype: int64

In [20]:
# Menampilkan data dengan missing values
df2[df2.isna().any(axis=1)]

Rk            Player    Pos           Squad  Age  Born  MP    Min  \
0      1      Amir Abrashi     MF      al Albania   33  1990   0    NaN   
1      2         Che Adams     FW    sct Scotland   27  1996   3  209.0   
2      3  Michel Aebischer     DF  ch Switzerland   27  1997   5  476.0   
3      4      Arlind Ajeti     DF      al Albania   30  1993   3  270.0   
4      5     Manuel Akanji     DF  ch Switzerland   28  1995   5  480.0   
..   ...               ...    ...             ...  ...   ...  ..    ...   
615  616  Andrija Živković     DF       rs Serbia   27  1996   3  244.0   
616  617   Budu Zivzivadze  FW,MF      ge Georgia   29  1994   2   18.0   
617  618      Steven Zuber     MF  ch Switzerland   32  1991   2   77.0   
619  620  Oleksandr Zubkov     FW      ua Ukraine   27  1996   1   24.0   
620  621       Nino Žugelj     FW     si Slovenia   23  2000   0    NaN   

     Mn/MP   Min%  ...  onGA  +/-  +/-90  On-Off  onxG  onxGA  xG+/-  xG+/-90  \
0      NaN    NaN  ...   NaN  NaN    NaN     NaN   NaN    NaN    NaN      NaN   
1     70.0   77.4  ...   4.0 -3.0  -1.29    1.66   0.7    2.8   -2.0    -0.88   
2     95.0   99.2  ...   4.0  4.0   0.76    0.76   6.5    4.9    1.6     0.30   
3     90.0  100.0  ...   5.0 -2.0  -0.67     NaN   2.4    5.7   -3.2    -1.07   
4     96.0  100.0  ...   4.0  4.0   0.75     NaN   6.7    4.9    1.8     0.37   
..     ...    ...  ...   ...  ...    ...     ...   ...    ...    ...      ...   
615   81.0   90.4  ...   2.0 -2.0  -0.74   -4.20   1.7    2.4   -0.7    -0.25   
616    9.0    5.0  ...   2.0 -2.0 -10.00   -9.74   0.2    1.9   -1.6    -8.20   
617   39.0   16.0  ...   1.0  0.0   0.00   -0.89   1.3    0.9    0.4     0.70   
619   24.0    8.9  ...   0.0  1.0   3.75    4.85   0.4    0.2    0.1     0.54   
620    NaN    NaN  ...   NaN  NaN    NaN     NaN   NaN    NaN    NaN      NaN   

     On-Off.1  Matches  
0         NaN  Matches  
1        1.23  Matches  
2       -5.09  Matches  
3         NaN  Matches  
4        0.37  Matches  
..        ...      ...  
615     -1.05  Matches  
616     -6.81  Matches  
617      0.40  Matches  
619      0.51  Matches  
620       NaN  Matches  

[479 rows x 29 columns]

Ada beberapa pendekatan untuk menangani _missing values_, berikut pendekatan yang umum digunakan:
* Mengisi _missing values_ dengan nilai tertentu menggunakan _method_ <code>fillna()</code>
* Menghapus (_drop_) baris atau kolom yang mengandung _missing values_. Gunakan <code>dropna()</code> untuk menghapus __baris__ yang mengandung _missing values_, dan <code>dropna(axis='columns')</code> untuk menghapus __kolom__ yang mengandung missing values. Setelah drop, jangan lupa untuk mereset index agar tetap terurut.

In [21]:
# Mengisi missing values dengan nilai modus

df2_fillna = df2.copy()
df2_fillna = df2_fillna.fillna(df2_fillna.mode().iloc[0])
df2_fillna.isna().sum()

Rk          0
Player      0
Pos         0
Squad       0
Age         0
Born        0
MP          0
Min         0
Mn/MP       0
Min%        0
90s         0
Starts      0
Mn/Start    0
Compl       0
Subs        0
Mn/Sub      0
unSub       0
PPM         0
onG         0
onGA        0
+/-         0
+/-90       0
On-Off      0
onxG        0
onxGA       0
xG+/-       0
xG+/-90     0
On-Off.1    0
Matches     0
dtype: int64

In [22]:
# Menghapus baris yang mengandung missing values

df2_drop_row = df2.copy()
df2_drop_row = df2_drop_row.dropna().reset_index(drop=True)
print(f"Jumlah baris tersisa adalah: {df2_drop_row.shape[0]}")
df2_drop_row.isna().sum()

Jumlah baris tersisa adalah: 142


Rk          0
Player      0
Pos         0
Squad       0
Age         0
Born        0
MP          0
Min         0
Mn/MP       0
Min%        0
90s         0
Starts      0
Mn/Start    0
Compl       0
Subs        0
Mn/Sub      0
unSub       0
PPM         0
onG         0
onGA        0
+/-         0
+/-90       0
On-Off      0
onxG        0
onxGA       0
xG+/-       0
xG+/-90     0
On-Off.1    0
Matches     0
dtype: int64

## Pertanyaan Pandas

Selamat, kamu telah mempelajari sebagian kecil dari Pandas. Kini, silakan beberapa pertanyaan di bawah untuk menguji serta meningkatkan pemahaman kamu mengenai Pandas. Kamu dipersilakan menambahkan cell code dan text untuk memperjelas jawaban.

### Nomor 1

Buka dataset `player_playing_time.csv` sebagai DataFrame. Ambil hanya kolom `Player`, `Pos`, `Squad`, `Age`, `MP`, `Min`, dan `Mn/MP`. Kemudian, tampilkan 10 baris pertama dari DataFrame tersebut.



In [ ]:
# Jawaban nomor 1


### Nomor 2

Deskripsi dataset Player Playing Time dengan kolom yang telah dipilih adalah sebagai berikut:
- **Player**: Nama pemain
- **Pos**: Posisi pemain {GK: goal keeper atau penjaga gawang, DF: defender atau pemain bertahan (bek), MF: midfielder atau gelandang, FW: forward atau pemain menyerang (striker)}
- **Squad**: Tim (negara) pemain
- **Age**: Usia pemain
- **MP**: Matches played, jumlah pertandingan yang dimainkan oleh pemain
- **Min**: Jumlah menit pemain bermain
- **Mn/MP**: Minutes per Match Played, rata-rata menit bermain dalam setiap pertandingan yang dimainkan

Tampilkan ukuran DataFrame terbaru (jumlah kolom dan jumlah baris), tipe data setiap kolom, serta statistik deskriptif untuk kolom-kolom di atas.

In [ ]:
# Jawaban nomor 2


### Nomor 3

Ada berapa tim atau negara unik dari dataframe tersebut? Berikan tiga negara dengan pemain paling banyak.

In [ ]:
# Jawaban nomor 3


### Nomor 4

Tampilkan rata-rata menit bermain per pertandingan (Mn/MP). Kemudian tampilkan data pemain yang memiliki menit bermain per pertandingan ia bermain yang lebih besar dari rata-rata menit bermain per pertandingan (Mn/MP) setiap pemain. Urutkan dari pemain yang memiliki menit bermain terendah (Min).

In [ ]:
# Jawaban nomor 4


### Nomor 5

Buat DataFrame baru dengan kolom yang sama seperti **Nomor 1** dengan menghapus seluruh baris yang memiliki nilai null. Tampilkan rata-rata menit bermain keseluruhan pemain (Min).

In [ ]:
# Jawaban nomor 5


### Nomor 6

Buat DataFrame baru dengan kolom yang sama seperti **Nomor 1 dan 5** dengan mengisi seluruh nilai null pada kolom Min dengan nilai minimum. Tampilkan rata-rata menit bermain keseluruhan pemain (Min).

In [ ]:
# Jawaban nomor 6


### Nomor 7

Apakah ada perbedaan nilai rata-rata dari nomor 5 dan 6? Mengapa demikian dan **wajib menyertakan** sumber yang mendukung jawabanmu.

Jawaban nomor 7

# **NumPy**

[***NumPy***](https://numpy.org/) adalah *library* Python yang umum digunakan untuk melakukan komputasi saintifik, pengolahan, serta analisis data numerik karena performa dan kemudahannya. *NumPy* menyediakan fungsi-fungsi *high-level* untuk melakukan berbagai perhitungan secara efisien, seperti penjumlahan, pengurutan, dan sebagainya pada struktur data yang disebut ***array***.


In [ ]:
# import library
import numpy as np

## Array NumPy

Secara umum, *array* pada NumPy merupakan struktur data yang mirip dengan List, tetapi memiliki kemampuan yang lebih kuat dan efisien. *Array* bisa memiliki lebih dari satu dimensi, yang mana elemennya bisa berarti sebuah *array* juga, yang bisa memiliki elemen *array* juga, dan begitupun seterusnya sehingga memungkinkan penyimpanan struktur data dengan dimensi yang kompleks.

Untuk membuat objek *array*, kita bisa menggunakan fungsi `array(n)` dengan `n` berupa koleksi seperti list, tuple, dan sebagainya seperti berikut:

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


Selain itu, terdapat fungsi bawaan untuk membuat objek *array* yang dapat digunakan sesuai kebutuhan.

In [ ]:
# Membuat array dengan nilai 0 sebanyak 5
print("np.zeros(5) : ", np.zeros(5))

# Membuat array dengan nilai 1 sebanyak 5
print("np.ones(5) : ", np.ones(5))

# Membuat array dengan nilai dalam range 1 sampai 10 dengan step sebesar 2
print("np.arange(1,10,2) : ", np.arange(1,10,2))

# Membuat array dengan nilai dalam range 1 sampai 10 sebanyak 4 dengan interval yang sama
print("np.linspace(1,10,4) : ", np.linspace(1,10,4))

np.zeros(5) :  [0. 0. 0. 0. 0.]
np.ones(5) :  [1. 1. 1. 1. 1.]
np.arange(1,10,2) :  [1 3 5 7 9]
np.linspace(1,10,4) :  [ 1.  4.  7. 10.]


Untuk membuat *array* multidimensi, kita dapat menyediakan *collection* sebagai berikut:

In [ ]:
multdim_arr = np.array([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]])
multdim_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Properti *Array*

Sama seperti *DataFrame* sebelumnya, *array* juga memiliki properti yang dapat dilihat melalui fungsi-fungsi berikut:

In [ ]:
print(multdim_arr)

print()

# Menunjukkan ukuran array
print("multdim_arr.size:", multdim_arr.size)

# Menunjukkan jumlah dimensi atau rank dari sebuah array
print("multdim_arr.ndim:", multdim_arr.ndim)

# Mengetahui ukuran dari setiap dimensi array
print("multdim_arr.shape:", multdim_arr.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

multdim_arr.size: 9
multdim_arr.ndim: 2
multdim_arr.shape: (3, 3)


## Tipe data *Array*

In [ ]:
# Mengecek tipe list
lst = [1,2,3,4,5]
print(f"type(lst): {type(lst)}")

# Mengecek tipe array
arr = np.array(lst)
print(f"type(arr): {type(arr)}")

# Mengecek tipe data dari array
print(f"arr.dtype: {arr.dtype}")

type(lst): <class 'list'>
type(arr): <class 'numpy.ndarray'>
arr.dtype: int64


## Mengakses dan memanipulasi elemen *Array*

Sama seperti list, kita bisa mengakses dan memanipulasi array seperti berikut:

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
multdim_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Mengakses elemen indeks ke-3 dari array
print(arr[3])

# Mengakses elemen baris ke-1 dan kolom ke-2 dari multi dimensi array
print(multdim_arr[1,2])

# Cara lain
print(multdim_arr[1][2])

4
6
6


In [ ]:
# Mengakses elemen dari indeks ke-2 sampai ke-4
arr[2:5]

array([3, 4, 5])

In [ ]:
# Menagkses elemen dari baris kedua, kolom 1 sampai 3
multdim_arr[1,0:3]

array([4, 5, 6])

In [ ]:
# Mengakses kolom kedua
multdim_arr[:,1]

array([2, 5, 8])

In [ ]:
# Mengubah value elemen ke-3 dan ke-5 dari array
arr[0] = 10
arr

array([10,  2,  3,  4,  5])

In [ ]:
# Mengubah value elemen ke-3 dan ke-5 dari array
arr[[2, 4]] = 10
arr

array([10,  2, 10,  4, 10])

In [ ]:
# Mengubah value elemen baris ke-2 dan kolom ke-3 dari multi dimensi array
multdim_arr[1,2] = 15
multdim_arr

array([[ 1,  2,  3],
       [ 4,  5, 15],
       [ 7,  8,  9]])

## Operasi matematika pada *Array*

In [ ]:
arr_1 = np.array([1,2,3,4,5])
arr_2 = np.array([6,7,8,9,10])

In [ ]:
# Menjumlahkan dua buah array
result = arr_1 + arr_2
result

array([ 7,  9, 11, 13, 15])

In [ ]:
# Mengurangkan dua buah array
result = arr_1 - arr_2
result

array([-5, -5, -5, -5, -5])

In [ ]:
# Menjumlahkan setiap elemen array dengan 10
result = arr_1 + 10
result

array([11, 12, 13, 14, 15])

In [ ]:
# Mengalikan setiap elemen array dengan 10
result = arr_1 * 10
result

array([10, 20, 30, 40, 50])

In [ ]:
# Perkalian dua buah array
result = arr_1 * arr_2
result

array([ 6, 14, 24, 36, 50])

In [ ]:
# Dot product dua buah array
result = np.dot(arr_1, arr_2)
result

130

Operasi pada *array* juga berlaku pada array multidimensi / matrix. Kita juga dapat mengetahui transpose dan inverse dari sebuah matrix melalui fungsi berikut:

In [ ]:
matrix = np.array([[1,2], [5,11]])
print(matrix)
print()

# Transpose matrix
print("Transpose:")
print(np.transpose(matrix))
print()

# Invers matrix
print("Invers:")
print(np.linalg.inv(matrix))

[[ 1  2]
 [ 5 11]]

Transpose:
[[ 1  5]
 [ 2 11]]

Invers:
[[11. -2.]
 [-5.  1.]]


## Operasi statistik pada *Array*

In [ ]:
stat_arr = np.array([7, 7, 6, 6, 5, 7, 5, 9, 4, 2, 4, 2, 7, 7, 7, 3, 4, 4, 8, 7, 8, 6,
       4, 1, 1])
stat_arr

array([7, 7, 6, 6, 5, 7, 5, 9, 4, 2, 4, 2, 7, 7, 7, 3, 4, 4, 8, 7, 8, 6,
       4, 1, 1])

In [ ]:
# Nilai rata-rata dari sebuah array
print("Nilai rata-rata : ", np.mean(stat_arr))

# Nilai maksimal dari sebuah array
print("Nilai maks : ", np.max(stat_arr))

# Nilai unik dari sebuah array
print("Nilai unik : ", np.unique(stat_arr))

#Sort nilai pada array
print("Sorted : ", np.sort(stat_arr))

Nilai rata-rata :  5.24
Nilai maks :  9
Nilai unik :  [1 2 3 4 5 6 7 8 9]
Sorted :  [1 1 2 2 3 4 4 4 4 4 5 5 6 6 6 7 7 7 7 7 7 7 8 8 9]


## Pertanyaan NumPy'

Jawab setiap pertanyaan di bawah ini. Jawaban boleh lebih dari 1 _cell_ dan juga kombinasi antara _cell_ kode atau _markdown_ jika memang diperlukan.

### Nomor 1



In [ ]:
arr_1 = np.array([1, 0, np.nan, 1, 100, 90, 1000, 'a', 'b', 'c', 'hello world'])
arr_1.dtype

dtype('<U32')

Jalankan cell di atas! Mengapa `arr_1.dtype` bertipe `U32` padahal terdapat elemen integer dan NaN? **Wajib menyertakan** sumber yang mendukung jawaban kamu.

Jawaban nomor 1


### Nomor 2

Terdapat beberapa *array* multidimensi sebagai berikut:

In [ ]:
A = np.array([[1, 4, 3, 2], [0, 2, 1, 4], [3, 0, 2, 1], [5, 1, 0, 2]])
B = np.array([[2, 1, 3, 4], [0, 3, 4, 1], [4, 2, 1, 0], [1, 3, 2, 5]])
C = np.array([[0, 3, 1, 4], [2, 0, 3, 1], [1, 2, 4, 0], [5, 1, 2, 3]])
D = np.array([[4, 2, 0, 1], [3, 1, 2, 0], [1, 4, 2, 3], [0, 5, 4, 1]])

Dari ketiga multidimensi array di atas, lakukanlah langkah-langkah berikut ini.
1. Cari absolute dari penjumlahan antara A dan C yang kemudian dikurangi hasil penjumlahan B dan D
2. Buat matrix baru yang isinya adalah hasil akar (square root) tiap elemen dari matrix pada langkah 1 yang setiap elemennya dikali 2
3. Jalankan operasi invers pada matrix pada langkah 2
4. Terapkan operasi dot product pada matrix pada langkah 3 dengan matrix B
5. Jalankan perkalian skalar pada matrix A dengan hasil dot product pada langkah 4
*hint*: anda dapat menggunakan fungsi `sqrt()`

Secara matematis, langkah di atas dapat dituliskan sebagai berikut.
1. $V = |A + C - (B + D)|$
2. $W =$ sqrt(sebuah matrix yang tiap elemennya adalah elemen V) * 2
3. $X = W^{-1}$
4. $K = X\cdot{B}$
5. $result = K*A$

In [ ]:
# Jawaban nomor 2


### Nomor 3

In [ ]:
arr_3 = np.array([11,95,75,24,9,68,72,32,54,86,0,44,94,8,12,34,58,32,28,31,63,98,54,31,75,66,60,78,77,47])

Untuk setiap elemen `arr_3`, jumlahkan dengan 10 dan kemudian hitung serta tampilkan rata-rata, median, nilai minimum, standar deviasi, variance, dan percentile 60!

In [ ]:
# Jawaban nomor 3
